name: mars_scanner
description: "Supabase auth App"
publish_to: 'none' 
version: 1.0.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  dio: ^5.3.3
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  fixnum: ^1.0.0
  flutter_screenutil: ^5.9.3
  synchronized: ^3.1.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  flutter_onboarding_slider: ^1.0.11
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.4
  flutter_animate: ^4.5.0
  graphql_flutter: ^5.2.0-beta.7
  hive: ^2.2.3
  flutter_hooks: ^0.20.5
  pdf: ^3.8.0
  share_plus: ^10.0.2
  open_file: ^3.2.1
  # flutter_media_downloader: ^1.0.5
  graphic:
  logging: ^1.2.0
  rxdart: ^0.28.0
  http: ^1.2.2
  flutter_cache_manager: ^3.4.1
  dio_cache_interceptor: ^3.5.0
  shimmer: ^3.0.0
  intl: ^0.20.0
  url_launcher: ^6.3.0
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.9.0
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5
  change_app_package_name: ^1.4.0
  flutter_secure_storage: ^9.2.2
  visibility_detector: ^0.4.0+2
  dio_cache_interceptor_hive_store: ^3.2.2
  animated_flip_counter: ^0.3.4
  rename_app: ^1.6.1
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_swipe_button: ^2.1.3
  haptic_feedback: ^0.5.1+1
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.1
  local_auth: ^2.1.8
  device_info_plus: ^9.1.2
  path: ^1.9.0
  no_screenshot: ^0.3.1
  cupertino_back_gesture: ^0.1.0
  app_links: ^6.1.4
  encrypt: ^5.0.3
  restart: ^1.0.0+1
  flutter_phoenix: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Onboarding/
    - assets/lottie/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400

    - family: VanguardCF
      fonts:
        - asset: assets/fonts/VanguardCF-ExtraBold.otf
          weight: 800
  
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Semibold.otf
          weight: 600
    
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 400

flutter_native_splash:
  color: "#141414"
  image: assets/images/background.png
  android: true
  android_12:
    color: "#141414"
    image: assets/images/background.png
