name: mars_scanner
description: "Mars Scanner App"
publish_to: 'none' 
version: 3.7.8

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_compress: ^3.1.4
  path_provider: ^2.1.1
  dio: ^5.3.3
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  fixnum: ^1.0.0
  flutter_screenutil: ^5.9.3
  video_player: ^2.9.1
  synchronized: ^3.1.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  flutter_onboarding_slider: ^1.0.11
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.4
  flutter_animate: ^4.5.0
  graphql_flutter: ^5.2.0-beta.7
  hive: ^2.2.3
  flutter_hooks: ^0.20.5
  pdf: ^3.8.0
  share_plus: ^10.0.2
  open_file: ^3.2.1
  # flutter_media_downloader: ^1.0.5
  graphic:
  logging: ^1.2.0
  rxdart: ^0.28.0
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_cache_manager: ^3.4.1
  pull_to_refresh: ^2.0.0
  dio_cache_interceptor: ^3.5.0
  shimmer: ^3.0.0
  intl: ^0.20.0
  url_launcher: ^6.3.0
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.9.0
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5
  change_app_package_name: ^1.4.0
  flutter_secure_storage: ^9.2.2
  visibility_detector: ^0.4.0+2
  dio_cache_interceptor_hive_store: ^3.2.2
  animated_flip_counter: ^0.3.4
  rename_app: ^1.6.1
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_swipe_button: ^2.1.3
  haptic_feedback: ^0.5.1+1
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  local_auth: ^2.1.8
  battery_plus: ^6.2.0
  device_info_plus: ^9.1.2
  path: ^1.9.0
  toggle_switch: ^2.3.0
  keyboard_detection: ^0.7.3
  screen_protector: ^1.4.2+1
  no_screenshot: ^0.3.1
  cupertino_back_gesture: ^0.1.0
  app_links: ^6.1.4
  encrypt: ^5.0.3
  file_picker: ^8.1.7
  dropdown_button2: ^2.3.9
  flutter_markdown: ^0.7.5
  flutter_phoenix: ^1.1.1
  firebase_analytics: ^11.4.2
  persona_flutter: ^3.2.8
  precached_network_image: ^1.2.4
  field_suggestion: ^0.2.6
  hive_flutter: ^1.1.0
  restart: ^1.0.0+1
  skeletonizer: ^1.4.3
  flutter_widget_from_html_core: ^0.16.0
  add_2_calendar: ^3.0.1
  device_calendar: ^4.3.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  timezone: ^0.9.4
  flutter_ntp: ^0.0.2
  barcode_widget: ^2.0.4
  cached_network_svg_image: ^1.2.0
  mobile_scanner: ^7.0.0
  flutter_barcode_scanner: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 23
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Home/
    - assets/images/
    - assets/images/artists/
    - assets/images/Home/
    - assets/images/Onboarding/
    - assets/videos/
    - assets/lottie/
    - assets/icons/
    - assets/svg/
    - assets/svg/prometrics/active_icons/
    - assets/svg/prometrics/Spotify/
    - assets/svg/prometrics/IG/
    - assets/svg/prometrics/Pandora/
    - assets/svg/prometrics/Soundcloud/
    - assets/svg/prometrics/Tiktok/
    - assets/svg/prometrics/Youtube/
    - assets/svg/prometrics/Apple/
    - assets/svg/careerstage/
    - assets/svg/recentmomentum/
    - assets/json/artists.json
    - assets/passkit/Generic.pkpass
    - assets/passkit/Mars.pkpass
    - assets/passkit/Event.pkpass
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400

    - family: VanguardCF
      fonts:
        - asset: assets/fonts/VanguardCF-ExtraBold.otf
          weight: 800
  
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Semibold.otf
          weight: 600
    
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 400

flutter_native_splash:
  color: "#141414"
  image: assets/images/background.png
  android: true
  android_12:
    color: "#141414"
    image: assets/images/background.png
